spring:
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

server:
  port: 8077
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true